# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Data Science for Scientists - a graduate level course
author: Dr. Yohai Bar-Sinai, School of Physics, Tel Aviv University
logo: tau_logo.jpg

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  timeout: 1000
  execute_notebooks: cache

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: "https://github.com/yohai/DataScienceCourse/"  # Online location of your book
  branch: master  # Which branch of the repository should be used when creating links (optional)
  
#Launch on colab
launch_buttons:
  notebook_interface: "classic" #"jupyterlab"  # or "classic"
  colab_url: "https://colab.research.google.com"
  binderhub_url:  "https://mybinder.org/v2/gh/BarakHirshberg/book/master"  # The URL for your BinderHub (e.g., https://mybinder.org)
  thebe: true

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

#use MathJax 3
sphinx:
  config:   
    mathjax3_config:
      tex:
        macros:
          "pa": '{\partial}'
          "avg": ['{\left\langle #1 \right\rangle}', 1]
          "pd": ['{\frac{\partial #1}{\partial #2}}', 2]
    
#use Latex-style math with the amsmath MyST extension
parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default!
    - amsmath
    - dollarmath
    - colon_fence  
